name: PetClinic Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  TAG: yusmadi/spring-petclinic:0.2
  DOCKER_USER: yusmadi

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & push image
      env:
        DOCKER_PASSWORD: ${{ secrets.docker_password }}
      run: |
        docker build . --file Dockerfile --tag $TAG
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        docker push $TAG
